apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry-kcrw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry-kcrw
    app.kubernetes.io/part-of: rhosr
  name: apicurio-registry-kcrw
  namespace: gbenhaim-stonesoup-ocm-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apicurio-registry-kcrw
    weight: 100
status: {}
